language: node.js
node_js:
  - "16"
script:
  - echo '***********Build starts***********'
  - echo 'Installing Dependencies'
  - npm install
  - echo 'Start app'
  - node app.js
  - echo 'Running tests'
  - mocha
