language: node_js
node_js:
  - '10'
dist: trusty
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm install --save-dev
script:
  - nohup npx json-server ./src/server/db.json
  - sleep 3
  - npm run lint
  - npm run test
  - npm run build
